year = input('year of your birth ? ')
age = 2020 - int(year)
print(age)
print("this is the result")
print(2 + 3)
name = input('name? ')
print('Hi ' + name)
color = input ('What is your favorite color? ')
print(name +"'s " + 'favourite color is ' + color)
print(type(name))
print(type(age))
